### ISSUE TITLE
Invalid WEP key length?

### ISSUE THREAD

**Issue by rjcoupe** [r4ulcl/WiFiChallengeLab-docker#8]
The WEP key length returned by cracking attempts against (and also found in the config file for) `wifi-old` is - as far as I'm aware - a nonstandard length, resulting in wpa_supplicant rejecting/ignoring config blocks containing it.

Recreating the config file as per the walkthrough and running the same `wpa_supplicant` call results in an error.

```
$ sudo wpa_supplicant -i wlan2 -c wifi-old.conf
Successfully initialized wpa_supplicant
Line 4: Invalid WEP key length <redacted> - this network block will be ignored
Line 4: Invalid WEP key length <redacted> - this network block will be ignored
```

This may not be an issue with the AP, per se, but it seems the docs may - at least - be missing something.

**Comment by r4ulcl** [comment]
Hi, are you using the VM from the lab or something different?

The configuration file and lab setup are correct, but there may be a problem with the WEP key you are using. The error you are seeing from wpa_supplicant indicates that the key length does not meet the expected standard for WEP. Make sure the password (WEP key) you are using is the correct length: 

- WEP keys for 64-bit encryption are exactly 10 hexadecimal digits long.

If the key you are using does not match this length, this is probably the cause of the problem. Double-check the key and try again. Let me know if it helps. The password is without the ‘:’
